### ISSUE TITLE
[REQUEST] Let the mercenary guild clerk pay off bounties

### ISSUE THREAD

**Issue by notafurryy** [Rotwood-Vale/Ratwood-Keep#1730]
## Describe the solution you'd like

as the title says, let the guild clerk pay off the roundstart bounties, gives an alternative to being under constant threat from a special or a flaw if you can get enough money to pay it back, also encourages mercenary guild rp rather than boring beheadings!

**Comment by ScienceMom** [comment]
This would be great. It'd give more of a reason for Excidium bounties to be brought alive rather than dead too, which is always fun RP. Rather than solely being able to pay off the bounties, it'd be nice if they could be paid off or have the payment withdrawn if the person with the bounty on their head is brought before an excidium by the guild clerk (To stop the bounty-havers from withdrawing their own bounty, or getting their friends to withdraw their bounty for them)
