### ISSUE TITLE
[BUG] you can't craft bottle bombs anymore 

### ISSUE THREAD

**Issue by zeratino** [Rotwood-Vale/Ratwood-Keep#2051]
## Describe the bug

since the essence update, alchemy crafting was gutted & you can no longer craft firebombs
this probably wouldn't be a problem if court physician and other roles had the alchemy skill, like they used to
## Round ID:

Tower1571-21.59.34

## Steps to Reproduce:

>attempt bottle bomb production
>realize u dont have any alchemy skill as the court phys

## Additional context

bottle bomb recipe
![image](https://github.com/user-attachments/assets/96d4be66-43d1-412c-b8a6-28d0b94b0438)

court phys skills
![image](https://github.com/user-attachments/assets/5a90d9eb-445b-4ccd-bf79-577cd2bb1d5a)

**Comment by Xaytan** [comment]
Is that why I haven't seen anyone use a bottle bomb recently? Huh.

**Comment by john-pawson** [comment]
Hey, the bottle bomb recipe uses treatment skill, which is the one used for all alchemical recipes/processes. Are you sure you can't create a bottle bomb? Because from my testing you're completely able to, you simply need an alembic nearby and apprentice treatment skill.

![image](https://github.com/user-attachments/assets/7f31041a-c881-475a-a85a-825aee8ea755)
![image](https://github.com/user-attachments/assets/0ad45549-c6f9-4986-a40d-2ae5f9ebca93)

If this happens on the actual live server for whatever reason, the problem isn't the lack of an alchemy skill, but something else.

**Comment by zeratino** [comment]
im retarded and didn't see that it required 2 pieces of ash now instead of 1
